# Generated by Django 4.2.9 on 2026-03-21 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jj', '0002_alter_contact_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='created_at',
        ),
    ]
