# Generated by Django 4.2.9 on 2026-04-07 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jj', '0004_colleges'),
    ]

    operations = [
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('logo', models.ImageField(upload_to='Colleges/')),
            ],
        ),
        migrations.DeleteModel(
            name='Colleges',
        ),
    ]
