# Generated by Django 4.2.9 on 2026-04-07 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jj', '0005_college_delete_colleges'),
    ]

    operations = [
        migrations.AddField(
            model_name='college',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='college',
            name='location',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
